# Generated by Django 6.0.3 on 2026-03-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proto_data', models.BinaryField()),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-inserted_at'],
            },
        ),
    ]
